version: '3.8'

services:
  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: storage_db
      HTTP_PORT: 8080
    networks:
      - appnet

  frontend-nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./web/dist:/usr/share/nginx/html:ro
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

  secure-proxy:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/secure-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storage_db
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - appnet

volumes:
  postgres: 

networks:
  appnet:
    driver: bridge