version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: storage
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storage_db
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres: 