openapi: 3.0.0
info:
  title: File Storage API
  version: 1.0.0
  description: API для хранения зашифрованных файлов

servers:
  - url: http://localhost:8080
    description: Локальный сервер разработки
  - url: https://api.example.com
    description: Продакшн сервер

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /login:
    post:
      summary: Вход пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "401":
          description: Неверные учетные данные

  /register:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: Пользователь создан
        "400":
          description: Неверные данные

  /logout:
    post:
      summary: Выход пользователя
      responses:
        "200":
          description: Успешный выход
        "401":
          description: Неавторизован

  /refresh:
    post:
      summary: Обновление токена
      responses:
        "200":
          description: Токен обновлён
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefreshResponse"

  /api/files/list:
    get:
      security:
        - bearerAuth: []
      summary: Получение списка файлов
      description: Возвращает список всех файлов с метаданными
      responses:
        '200':
          description: Список файлов
          content:
            application/json:
              schema:
                type: object
                properties:
                  files:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Имя файла
                        created_at:
                          type: string
                          format: date-time
                          description: Дата создания
                        updated_at:
                          type: string
                          format: date-time
                          description: Дата обновления
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/files/upload:
    post:
      security:
        - bearerAuth: []
      summary: Загрузка зашифрованного файла
      description: Загружает зашифрованный файл вместе с ключом и вектором инициализации
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Зашифрованный файл (AES-256-GCM)
                key:
                  type: string
                  format: binary
                  description: Зашифрованный AES ключ (через GPG/Yubikey)
                nonce:
                  type: string
                  format: binary
                  description: Вектор инициализации для AES-GCM (12 байт)
                filename:
                  type: string
                  description: Оригинальное имя файла
              required:
                - file
                - key
                - nonce
                - filename
      responses:
        '200':
          description: Файл успешно загружен
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  filename:
                    type: string
        '400':
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/files/download/{filename}:
    get:
      security:
        - bearerAuth: []
      summary: Скачивание зашифрованного файла
      description: Возвращает зашифрованный файл, ключ и вектор инициализации
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
          description: Имя файла для скачивания
      responses:
        '200':
          description: Зашифрованные данные файла
          content:
            application/json:
              schema:
                type: object
                properties:
                  file:
                    type: array
                    items:
                      type: integer
                    description: Зашифрованные данные файла
                  key:
                    type: array
                    items:
                      type: integer
                    description: Зашифрованный AES ключ
                  nonce:
                    type: array
                    items:
                      type: integer
                    description: Вектор инициализации
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Файл не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/files/delete/{filename}:
    delete:
      security:
        - bearerAuth: []
      summary: Удаление файла
      description: Удаляет файл и его метаданные
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
          description: Имя файла для удаления
      responses:
        '200':
          description: Файл успешно удален
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Файл не найден
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 6
      required:
        - email
        - password

    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
        user:
          $ref: "#/components/schemas/UserInfo"

    UserInfo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
          format: email

    RefreshResponse:
      type: object
      properties:
        access_token:
          type: string